name: Deploy Website to Apache Server

on:
  push:
    branches:
      - main  # Trigger this workflow on pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Public IP of Server
        id: ip-fetch
        run: |
          # Fetch the public IP of your server using icanhazip.com
          SERVER_IP=$(curl -s icanhazip.com)
          echo "Server IP is: $SERVER_IP"
          # Store the fetched IP in an environment variable
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy website files to server
        run: |
          # Use the dynamically fetched IP address in SCP command
          scp -r ./ * ubuntu@${{ env.SERVER_IP }}:/var/www/ersmp.net

      - name: Restart Apache to apply changes
        run: |
          # Use the fetched IP to SSH into the server and restart Apache
          ssh ubuntu@${{ env.SERVER_IP }} 'sudo systemctl restart apache2'
